- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:OverallPlaytimeRequirement #DeltaV
      time: 1
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External
  - Corpsman
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: BrigmedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesNitrile
    eyes: ClothingEyesHudMedical
    head: ClothingHeadHatBeretBrigmedic
    id: BrigmedicPDA
    neck: ClothingNeckScarfStripedRed
    outerClothing: ClothingOuterWinterSec
    ears: ClothingHeadsetBrigmedic
    mask: ClothingMaskBreathMedicalSecurity
    belt: ClothingBeltMedicalFilled
  innerClothingSkirt: ClothingUniformJumpskirtBrigmedic
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
